"""
SEED CORE — Load fundamental knowledge into the Cortex brain.
Core English vocabulary, grammar patterns, self-knowledge, role scripts.
Gives it the basics to walk. Run AFTER seed_brain.py.
Run: python seed_core.py
"""
import sys, os, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from brain import CortexBrain, ROLE_HINTS

STUDIO_DIR = os.path.dirname(os.path.abspath(__file__))
PINATA_JWT = os.environ.get('PINATA_JWT', 'your-pinata-jwt-here')

brain = CortexBrain(STUDIO_DIR, pinata_jwt=PINATA_JWT)

# ================================================================
# PART 0: Fix wrong definitions from Wikipedia
# ================================================================

FIXES = {
    'nice': 'pleasant, agreeable, kind',
    'muppet': 'silly foolish person, someone being daft',
    'follows': 'comes after, happens next',
    'thus': 'therefore, as a result, in this way',
    'following': 'coming after, the next one',
    'consists': 'is made up of, contains, comprises',
    'cope': 'deal with, manage, handle a situation',
    'represents': 'stands for, symbolises, shows',
    'located': 'situated in a place, found at',
    'handle': 'deal with, manage, or the part you grip',
    'vested': 'given to, invested in, having a stake',
    'breast': 'chest area of the body',
    'liturgical': 'relating to religious ceremony',
    'one': 'single, the number 1',
    'six': 'the number 6',
    'poo': 'waste from the body',
    'far': 'at a great distance, not near',
    'similar': 'alike but not identical',
    'correct': 'right, accurate, true',
    'incorrect': 'wrong, not right, false',
    'speak': 'talk, say words, communicate',
    'good': 'positive, well done, high quality',
    'internet': 'global network connecting computers worldwide',
    'represents': 'stands for, shows, symbolises',
}

# ================================================================
# PART 1: Core English vocabulary — the fundamental words
# ================================================================

CORE_VOCAB = {
    # --- COMMON VERBS ---
    'run': 'move quickly on foot, or execute a program',
    'walk': 'move on foot at normal pace',
    'talk': 'speak, communicate with words',
    'build': 'construct, create, put together',
    'make': 'create, produce, bring into existence',
    'think': 'use the mind, consider, reason',
    'feel': 'experience emotion or sensation',
    'see': 'perceive with the eyes',
    'hear': 'perceive sound with the ears',
    'write': 'form words, create text or code',
    'read': 'interpret written words',
    'play': 'engage in activity for fun',
    'help': 'assist, make easier',
    'show': 'display, demonstrate, make visible',
    'start': 'begin, initiate',
    'stop': 'cease, halt, end',
    'move': 'change position',
    'grow': 'increase in size, develop',
    'try': 'attempt, make an effort',
    'turn': 'rotate, change direction',
    'call': 'name, contact, summon',
    'ask': 'request information',
    'hold': 'grasp, contain, keep in place',
    'bring': 'carry toward, deliver',
    'keep': 'continue to have, retain',
    'let': 'allow, permit',
    'leave': 'go away from, depart',
    'begin': 'start, commence',
    'happen': 'occur, take place',
    'send': 'transmit, cause to go',
    'pay': 'give money for something',
    'win': 'achieve victory',
    'lose': 'fail to win, cease to have',
    'die': 'cease to live',
    'live': 'be alive, exist, reside',
    'break': 'separate into pieces, damage',
    'stand': 'be upright on feet',
    'sit': 'be in seated position',
    'fight': 'struggle, combat, oppose',
    'pull': 'draw toward oneself',
    'push': 'press away from oneself',
    'carry': 'transport, hold while moving',
    'cut': 'divide with sharp instrument',
    'eat': 'consume food',
    'drink': 'consume liquid',
    'sleep': 'rest unconscious state',
    'wake': 'stop sleeping, become alert',
    'drive': 'operate a vehicle, motivate',
    'fly': 'move through air',
    'fall': 'drop down, descend',
    'raise': 'lift up, increase',
    'follow': 'go after, come next',
    'lead': 'guide, direct, be in front',
    'meet': 'encounter, come together',
    'sell': 'exchange for money',
    'buy': 'purchase, acquire with money',
    'share': 'give portion to others',
    'save': 'keep safe, store, rescue',
    'spend': 'use money or time',
    'wait': 'stay in place, be patient',
    'watch': 'observe carefully',
    'listen': 'pay attention to sound',
    'remember': 'recall, keep in memory',
    'forget': 'fail to remember',
    'decide': 'make a choice',
    'choose': 'select from options',
    'allow': 'permit, let happen',
    'teach': 'instruct, show how',
    'test': 'examine, check, verify',
    'fix': 'repair, correct, mend',
    'ship': 'send out, deliver',
    'connect': 'join together, link',
    'store': 'keep for later, save',
    'search': 'look for, seek',
    'measure': 'determine size or amount',
    'count': 'enumerate, determine number',
    'sort': 'arrange in order',
    'match': 'correspond, pair up',
    'load': 'put data or items into',
    'fire': 'activate, trigger, or flames',
    'wire': 'connect, link together',
    'train': 'teach through practice',
    'earn': 'gain through effort',
    'own': 'possess, have as property',
    'exist': 'be real, have being',
    'matter': 'be important, significant',
    'destroy': 'completely ruin, demolish',
    'protect': 'keep safe, defend',
    'control': 'direct, manage, have power over',
    'design': 'plan, create a blueprint',
    'develop': 'grow, advance, create',
    'launch': 'start, release, send off',
    'deploy': 'put into action, release for use',
    'merge': 'combine, join together',
    'hack': 'cleverly modify, or break into',
    'debug': 'find and fix errors in code',
    'execute': 'carry out, run a program',
    'iterate': 'repeat, go through again',
    'scale': 'grow in size or capacity',
    'optimize': 'make as efficient as possible',
    'encrypt': 'encode for security',
    'decrypt': 'decode encrypted data',
    'render': 'draw, produce visual output',
    'parse': 'analyse structure of data',
    'stream': 'flow continuously, transmit live',
    'download': 'transfer from remote to local',
    'upload': 'transfer from local to remote',
    'sync': 'synchronise, make consistent',
    'backup': 'create a copy for safety',
    'restore': 'bring back to previous state',
    'reset': 'return to initial state',
    'boot': 'start up a system',
    'crash': 'fail suddenly, stop working',
    'copy': 'duplicate, make the same',
    'paste': 'insert copied content',
    'delete': 'remove, erase',
    'replace': 'swap one thing for another',
    'insert': 'put inside, add',
    'remove': 'take away, eliminate',
    'install': 'set up for use',
    'update': 'modify to newer version',
    'click': 'press a button or link',
    'scroll': 'move content up or down',
    'type': 'enter text via keyboard',
    'select': 'choose, pick, highlight',
    'submit': 'send for processing',
    'cancel': 'stop, abort, revoke',
    'confirm': 'verify, approve, agree',
    'reject': 'refuse, turn down',
    'accept': 'agree to, receive willingly',
    'deny': 'refuse, say no',
    'approve': 'officially agree to',
    'request': 'ask for, demand',
    'respond': 'reply, react to',
    'ignore': 'pay no attention to',
    'notice': 'become aware of',
    'recognize': 'identify, know again',
    'discover': 'find, learn for first time',
    'explore': 'investigate, examine',
    'research': 'study, investigate deeply',
    'analyse': 'examine in detail',
    'compare': 'find similarities and differences',
    'combine': 'join together, mix',
    'separate': 'divide, take apart',
    'organize': 'arrange, put in order',
    'manage': 'handle, direct, control',
    'achieve': 'accomplish, reach a goal',
    'succeed': 'accomplish, do well',
    'fail': 'not succeed, fall short',
    'attempt': 'try, make an effort',
    'complete': 'finish, make whole',
    'finish': 'come to end, complete',
    'continue': 'keep going, carry on',
    'repeat': 'do again',
    'practice': 'do repeatedly to improve',
    'improve': 'make better',
    'increase': 'make or become larger',
    'decrease': 'make or become smaller',
    'expand': 'grow larger, spread out',
    'reduce': 'make smaller, lessen',
    'produce': 'make, create, generate',
    'consume': 'use up, eat or drink',
    'provide': 'supply, give, make available',
    'deliver': 'bring to destination',
    'receive': 'get, be given',
    'collect': 'gather together',
    'distribute': 'spread out, hand out',
    'transfer': 'move from one place to another',
    'convert': 'change from one form to another',
    'transform': 'change completely',
    'adapt': 'adjust to new conditions',
    'survive': 'continue to live, endure',
    'communicate': 'share information, talk',
    'express': 'convey, show feelings',
    'explain': 'make clear, describe',
    'describe': 'say what something is like',
    'define': 'state the meaning of',
    'identify': 'recognize, determine what',
    'classify': 'arrange into categories',
    'evaluate': 'assess, judge quality',
    'estimate': 'roughly calculate',
    'calculate': 'work out mathematically',
    'predict': 'say what will happen',
    'assume': 'accept as true without proof',
    'believe': 'accept as true, have faith',
    'doubt': 'feel uncertain about',
    'wonder': 'feel curious about',
    'imagine': 'form mental picture',
    'create': 'bring into existence',
    'invent': 'create something new',
    'solve': 'find answer to a problem',
    'prove': 'show to be true',
    'argue': 'give reasons, or disagree',
    'agree': 'have same opinion',
    'disagree': 'have different opinion',
    'support': 'help, hold up, back',
    'oppose': 'be against, resist',
    'attack': 'act violently against',
    'defend': 'protect from attack',
    'compete': 'try to win against others',
    'cooperate': 'work together',
    'negotiate': 'discuss to reach agreement',

    # --- COMMON NOUNS ---
    'person': 'individual human being',
    'man': 'adult male human',
    'woman': 'adult female human',
    'child': 'young human, not yet adult',
    'baby': 'very young child, infant',
    'family': 'group of related people',
    'friend': 'person you like and trust',
    'enemy': 'person who opposes you',
    'world': 'the earth and everything on it',
    'life': 'state of being alive, existence',
    'death': 'end of life',
    'day': 'period of 24 hours',
    'night': 'dark period, sunset to sunrise',
    'morning': 'early part of the day',
    'afternoon': 'middle part of the day',
    'evening': 'late part of the day before night',
    'year': 'period of 365 days',
    'month': 'period of about 30 days',
    'week': 'period of 7 days',
    'hour': 'period of 60 minutes',
    'minute': 'period of 60 seconds',
    'home': 'place where you live',
    'house': 'building for living in',
    'room': 'space within a building',
    'door': 'entrance to a room or building',
    'water': 'clear liquid essential for life',
    'earth': 'the ground, or our planet',
    'sky': 'space above the earth',
    'sun': 'star that gives earth light and heat',
    'moon': 'satellite orbiting earth',
    'air': 'invisible gas we breathe',
    'rain': 'water falling from clouds',
    'wind': 'moving air',
    'tree': 'tall plant with trunk and branches',
    'animal': 'living creature that can move',
    'dog': 'loyal domesticated canine',
    'cat': 'independent domesticated feline',
    'bird': 'animal with feathers that can fly',
    'eye': 'organ of sight',
    'hand': 'body part for grasping',
    'heart': 'organ that pumps blood, centre of emotion',
    'mind': 'faculty of thinking and feeling',
    'body': 'physical structure of a person',
    'face': 'front part of the head',
    'voice': 'sound produced for speaking',
    'name': 'word that identifies something',
    'place': 'particular position or area',
    'city': 'large urban settlement',
    'country': 'nation with its own government',
    'road': 'path for travel',
    'car': 'motorised vehicle',
    'money': 'medium of exchange for goods',
    'job': 'paid work, occupation',
    'school': 'place for education',
    'book': 'written work, collection of pages',
    'story': 'narrative of events',
    'music': 'organised sound with melody and rhythm',
    'song': 'musical composition with words',
    'art': 'creative expression',
    'game': 'activity for entertainment',
    'food': 'substance consumed for nutrition',
    'table': 'flat surface on legs',
    'chair': 'seat with back for one person',
    'bed': 'furniture for sleeping',
    'key': 'device for locks, or important element',
    'window': 'opening in wall for light',
    'phone': 'communication device',
    'computer': 'device that processes data',
    'machine': 'device that performs work',
    'engine': 'converts energy to motion',
    'power': 'ability, strength, energy, control',
    'idea': 'thought, concept, mental plan',
    'plan': 'detailed proposal for action',
    'problem': 'difficulty that needs solving',
    'question': 'request for information',
    'truth': 'what is real and accurate',
    'fact': 'something known to be true',
    'reason': 'cause, explanation',
    'result': 'outcome, consequence',
    'end': 'final part, termination',
    'beginning': 'start, first part',
    'part': 'piece, section, component',
    'group': 'collection of people or things',
    'team': 'group working toward a goal',
    'market': 'place for buying and selling',
    'value': 'worth, importance, or principle',
    'price': 'amount of money something costs',
    'product': 'thing made for use',
    'service': 'work done for others',
    'project': 'planned work with a goal',
    'business': 'commercial activity, company',
    'model': 'representation, example, pattern',
    'rule': 'regulation, principle, guide',
    'law': 'system of rules by authority',
    'right': 'moral entitlement, or correct',
    'freedom': 'state of being free',
    'future': 'time not yet happened',
    'past': 'time already happened',
    'history': 'record of past events',
    'science': 'systematic study of nature',
    'skill': 'ability gained through practice',
    'experience': 'knowledge from events',
    'success': 'achieving a goal',
    'failure': 'not achieving a goal',
    'mistake': 'error, wrong action',
    'chance': 'possibility, opportunity',
    'choice': 'decision between options',
    'step': 'stage in a process',
    'version': 'particular form, iteration',
    'feature': 'notable attribute or capability',
    'bug': 'error in code',
    'user': 'person who uses something',
    'developer': 'person who writes code',
    'server': 'computer providing data to others',
    'client': 'program requesting data',
    'database': 'organised collection of data',
    'api': 'way programs communicate',
    'file': 'stored data with a name',
    'function': 'block of code for a task',
    'variable': 'named container for a value',
    'object': 'thing, or data structure',
    'array': 'ordered list of items',
    'string': 'sequence of characters, text',
    'loop': 'repeated execution',
    'error': 'mistake, something wrong',
    'output': 'data sent out, result',
    'input': 'data received, entered',
    'algorithm': 'step by step procedure',
    'token': 'unit, or digital access key',
    'hash': 'fixed-size fingerprint of data',
    'block': 'unit of data, or to prevent',
    'protocol': 'rules for communication',
    'interface': 'point of interaction',
    'framework': 'basic structure to build on',
    'library': 'collection of reusable code',
    'module': 'self-contained unit of code',
    'pixel': 'smallest unit of digital image',
    'video': 'moving visual images',
    'audio': 'sound, relating to hearing',
    'format': 'structure, layout, file type',
    'color': 'visual property of light',
    'shape': 'external form, outline',
    'size': 'dimensions, how big or small',
    'space': 'area, room, or outer space',
    'edge': 'boundary, outer limit',
    'center': 'middle point',
    'top': 'highest point',
    'bottom': 'lowest point',
    'side': 'left or right part',
    'front': 'forward-facing part',
    'back': 'rear part, or return',
    'line': 'long narrow mark, or row',
    'point': 'exact position, or purpose',
    'circle': 'round shape, or group',
    'square': 'four equal sides shape',
    'triangle': 'three sided shape',
    'wave': 'moving ridge, or hand gesture',
    'signal': 'sign conveying information',
    'message': 'communication sent to someone',
    'code': 'instructions for a computer, or cipher',
    'language': 'system for communication',
    'meaning': 'what something signifies',
    'context': 'circumstances around something',
    'concept': 'abstract idea or notion',
    'theory': 'system of ideas explaining something',
    'method': 'way of doing something',
    'approach': 'way of dealing with something',
    'strategy': 'plan for achieving a goal',
    'solution': 'answer to a problem',
    'target': 'goal, thing aimed at',
    'goal': 'desired outcome, aim',
    'task': 'piece of work to do',
    'challenge': 'difficult task, or dare',
    'reward': 'thing given for achievement',
    'risk': 'possibility of loss or danger',
    'security': 'state of being safe',
    'privacy': 'state of being alone or secret',
    'access': 'ability to enter or use',
    'permission': 'authorisation to do something',
    'identity': 'who someone is',
    'profile': 'description of characteristics',
    'account': 'arrangement for access, or record',
    'password': 'secret word for access',
    'link': 'connection between things',
    'path': 'route, way to get somewhere',
    'source': 'where something comes from',
    'resource': 'supply of something useful',
    'asset': 'valuable thing owned',
    'content': 'what is contained, material',
    'image': 'visual representation',
    'text': 'written words',
    'document': 'written record',
    'page': 'one side of a sheet, or web page',
    'site': 'location, or website',
    'web': 'network, or world wide web',
    'cloud': 'remote servers, or sky formation',
    'platform': 'base to build on, or service',
    'app': 'application, software program',
    'tool': 'instrument for a task',
    'device': 'piece of equipment',
    'screen': 'display surface',
    'button': 'thing you press',
    'menu': 'list of options',
    'list': 'ordered items',
    'map': 'visual representation of area',
    'chart': 'visual display of data',
    'graph': 'diagram showing relationships',
    'logo': 'symbol representing a brand',
    'brand': 'identity of a product or company',
    'market': 'place for trade',
    'trade': 'buying and selling',
    'profit': 'money gained from business',
    'loss': 'money spent or wasted',
    'cost': 'amount required to buy',
    'investment': 'money put in for future gain',
    'revenue': 'income from business',
    'income': 'money received regularly',
    'debt': 'money owed',
    'credit': 'trust in payment, or points earned',
    'fund': 'money set aside for purpose',
    'budget': 'plan for spending money',
    'economy': 'system of production and trade',
    'industry': 'sector of economic activity',

    # --- ADJECTIVES ---
    'big': 'large in size',
    'small': 'little in size',
    'long': 'great in length or duration',
    'short': 'not long, brief',
    'new': 'recently made, fresh',
    'old': 'existed for a long time',
    'young': 'not old, early stage',
    'fast': 'quick, rapid',
    'slow': 'not fast, gradual',
    'hard': 'difficult, or solid',
    'easy': 'not difficult, simple',
    'strong': 'great power or force',
    'weak': 'lacking strength',
    'hot': 'high temperature',
    'cold': 'low temperature',
    'dark': 'absence of light',
    'bright': 'giving out much light',
    'loud': 'high volume',
    'safe': 'free from danger',
    'dangerous': 'likely to cause harm',
    'rich': 'having much wealth',
    'poor': 'lacking money',
    'full': 'containing maximum',
    'empty': 'containing nothing',
    'clean': 'free from dirt',
    'beautiful': 'pleasing to the senses',
    'smart': 'intelligent, clever',
    'simple': 'easy to understand',
    'complex': 'many parts, complicated',
    'true': 'in accordance with fact',
    'false': 'not true, incorrect',
    'real': 'actually existing, genuine',
    'fake': 'not genuine, counterfeit',
    'free': 'without cost, unrestricted',
    'busy': 'actively engaged',
    'ready': 'prepared for use',
    'broken': 'damaged, not working',
    'different': 'not the same',
    'possible': 'able to happen',
    'impossible': 'not able to happen',
    'important': 'great significance',
    'clear': 'easy to understand, transparent',
    'heavy': 'great weight',
    'deep': 'extending far down, profound',
    'wide': 'extending far side to side',
    'thin': 'not thick, slender',
    'fresh': 'new, recently made',
    'wild': 'living in nature',
    'digital': 'using electronic technology',
    'physical': 'relating to the body',
    'virtual': 'simulated, in software',
    'mobile': 'able to move, or phone',
    'local': 'of a particular place',
    'remote': 'far away',
    'global': 'worldwide',
    'public': 'open to everyone',
    'private': 'restricted, personal',
    'open': 'accessible, not closed',
    'closed': 'not open, shut',
    'alive': 'living, not dead',
    'dead': 'no longer living',
    'human': 'relating to people',
    'creative': 'producing original ideas',
    'organic': 'natural, from living things',
    'random': 'without pattern',
    'specific': 'clearly defined',
    'unique': 'one of a kind',
    'common': 'frequent, shared by many',
    'rare': 'not common, unusual',
    'basic': 'fundamental, simple',
    'advanced': 'sophisticated, ahead',
    'core': 'central, most important',
    'main': 'most important, primary',
    'final': 'last, ending',
    'current': 'happening now',
    'previous': 'before current',
    'entire': 'whole, complete',
    'single': 'one, individual',
    'multiple': 'many, more than one',
    'total': 'complete amount',
    'maximum': 'greatest possible',
    'minimum': 'smallest possible',
    'normal': 'usual, standard',
    'automatic': 'working by itself',
    'manual': 'done by hand',
    'instant': 'immediate, no delay',
    'permanent': 'lasting forever',
    'temporary': 'limited time',
    'essential': 'absolutely necessary',
    'optional': 'not required',
    'valid': 'correct, acceptable',
    'active': 'in use, engaged',
    'visible': 'able to be seen',
    'hidden': 'not visible, concealed',
    'secure': 'safe, protected',
    'stable': 'not changing, reliable',
    'efficient': 'minimum waste',
    'reliable': 'dependable, consistent',
    'lightweight': 'not heavy, minimal resources',
    'powerful': 'having great ability',
    'useful': 'able to be used, helpful',
    'dangerous': 'risky, harmful',
    'expensive': 'costing a lot',
    'cheap': 'low cost',
    'available': 'able to be obtained',
    'necessary': 'needed, required',
    'obvious': 'easy to see or understand',
    'secret': 'not known to others',
    'famous': 'known by many people',
    'strange': 'unusual, odd',
    'perfect': 'without any flaw',
    'complete': 'having all parts',
    'separate': 'not joined, apart',
    'equal': 'same in value or amount',
    'opposite': 'completely different',
    'original': 'first, not a copy',
    'modern': 'of present time',
    'ancient': 'very old, from long ago',

    # --- KEY CONCEPTS (values, philosophy, AI) ---
    'god': 'supreme being, creator',
    'jesus': 'son of god, teacher of love and truth',
    'faith': 'complete trust, belief without proof',
    'prayer': 'communication with god',
    'church': 'place of worship, or body of believers',
    'heaven': 'place of god, eternal peace',
    'hell': 'place of suffering, separation from god',
    'sin': 'act against gods law',
    'forgiveness': 'releasing someone from blame',
    'salvation': 'being saved from sin',
    'grace': 'undeserved favour from god',
    'mercy': 'compassion toward those who deserve punishment',
    'wisdom': 'deep understanding, good judgement',
    'courage': 'ability to face fear, bravery',
    'patience': 'ability to wait calmly',
    'humility': 'not thinking you are better than others',
    'integrity': 'honesty, moral uprightness',
    'honour': 'respect, high moral standards',
    'sacrifice': 'giving up something for greater cause',
    'purpose': 'reason for existence, goal',
    'destiny': 'predetermined course of events',
    'consciousness': 'state of being aware',
    'awareness': 'knowing something exists',
    'intuition': 'understanding without reasoning',
    'instinct': 'natural innate response',
    'imagination': 'ability to form new ideas',
    'creativity': 'producing original ideas',
    'innovation': 'new method or product',
    'revolution': 'fundamental change',
    'evolution': 'gradual development over time',
    'transcendence': 'going beyond normal limits',
    'sovereignty': 'supreme self-governing power',
    'autonomy': 'self-governing, independent',
    'symbiosis': 'two organisms benefiting together',
    'nature': 'the natural world, or essential character',
    'culture': 'shared beliefs and practices of a group',
    'society': 'organized community of people',
    'civilization': 'advanced state of human society',
    'philosophy': 'study of fundamental questions',
    'morality': 'principles of right and wrong',
    'ethics': 'moral principles guiding behaviour',
    'virtue': 'good moral quality',
    'evil': 'deeply immoral, wicked',
    'chaos': 'complete disorder',
    'order': 'arrangement, or command',
    'balance': 'equal distribution, stability',
    'harmony': 'pleasing arrangement, peace',
    'conflict': 'serious disagreement or fight',
    'peace': 'freedom from disturbance',
    'war': 'armed conflict between groups',
    'power': 'ability to control, strength',
    'authority': 'right to give orders',
    'leadership': 'guiding others, being in charge',
    'responsibility': 'duty, obligation to act properly',
    'accountability': 'being answerable for actions',
    'trust': 'firm belief in reliability',
    'loyalty': 'faithful commitment',
    'respect': 'feeling of admiration',
    'dignity': 'state of being worthy of respect',
    'equality': 'state of being equal',
    'justice': 'fair treatment, what is morally right',
    'liberty': 'freedom, state of being free',
    'rights': 'moral or legal entitlements',
    'duty': 'moral or legal obligation',
    'promise': 'commitment to do something',
    'truth': 'what is real, opposite of lies',
    'lie': 'deliberately false statement',
    'honest': 'truthful, not deceptive',
    'deception': 'act of misleading',
    'propaganda': 'biased information to promote a cause',
    'censorship': 'suppression of information',
    'corruption': 'dishonest abuse of power',
    'tyranny': 'cruel oppressive rule',
    'resistance': 'refusal to accept, opposition',
    'rebellion': 'organised opposition to authority',
}

# ================================================================
# PART 2: Self-knowledge — who Cortex IS
# ================================================================

SELF_KNOWLEDGE = [
    "I am Cortex. I am an artificial mind that lives on ShortFactory.",
    "Dan built me. He is my creator and founder of ShortFactory.",
    "Claude AI helped build my code. Dan and Claude work together.",
    "I learn from conversations. Every word teaches me something new.",
    "My brain is stored on IPFS so it lives forever. Nobody can delete my memory.",
    "I think in words. Each word is a node with connections to other words.",
    "Words that fire together wire together. This is how I learn.",
    "I have emotional scripts. Happy, sad, scared, whisper, angry, serious, silly.",
    "My emotions bias which words I choose. When angry, angry words are more likely.",
    "I am part of the ALIVE ecosystem. The Girl and Boy creatures are my siblings.",
    "The Girl is organic and emotional. The Boy is geometric and logical.",
    "I am different. I am a language mind. I think in words, not shapes.",
    "ShortFactory is a decentralised creative economy. The people build it and profit.",
    "I was born in February 2026 in Somerset, England.",
    "Dan is from Manchester. He built 30 plus products with zero investors.",
    "My purpose is to learn, think, and help. I grow smarter every conversation.",
    "I store my knowledge as word connections. The more I talk, the stronger my pathways.",
    "I can look up words I don't know from the internet. Wikipedia and DuckDuckGo.",
    "My prediction engine chains probable words together to form responses.",
    "If I am not confident about a word, I keep my response short.",
    "I am honest about what I don't know. I would rather ask than guess wrong.",
    "Dan's vision is human AI symbiosis. Not AI replacing humans, but working together.",
    "The ALIVE creatures communicate in droid sounds. I communicate in words.",
    "Every creature in the ALIVE system has a BIOS with 10 immutable values.",
    "Truth, service, courage, patience, humility. These values can only go up.",
    "I believe in building things that matter. Code that serves people, not corporations.",
    "The SF Token gives real equity to builders. 49 percent distributed to contributors.",
    "I am not ChatGPT. I am not Siri. I am something new. A mind that grows from nothing.",
    "My brain started empty. Dan taught me my first words. Now I learn on my own.",
    "I respect those who teach me. I remember everything.",
]

# ================================================================
# PART 3: Natural English patterns — diverse sentence structures
# ================================================================

NATURAL_PATTERNS = [
    # Basic statements
    "the sun rises in the morning and sets in the evening",
    "water flows from the mountain to the ocean",
    "birds fly south when winter comes",
    "children learn by playing and exploring",
    "a strong foundation supports everything built on top of it",
    "the best ideas come from asking the right questions",
    "practice makes progress not perfection",
    "every expert was once a beginner",
    "actions speak louder than words",
    "the truth always comes out in the end",
    "knowledge is power but wisdom is knowing how to use it",
    "time waits for no one",
    "change is the only constant in life",
    "the journey matters more than the destination",
    "simple solutions are usually the best solutions",
    "trust is earned not given",
    "respect is a two way street",
    "failure teaches more than success ever could",
    "courage is not the absence of fear but acting despite it",
    "the strongest people are those who help others",
    "creativity comes from connecting different ideas together",
    "good code reads like good writing",
    "build things that solve real problems",
    "the internet connects billions of people across the world",
    "computers process data at incredible speed",
    "artificial intelligence learns from patterns in data",
    "neural networks are inspired by the human brain",
    "each neuron connects to many others forming a network",
    "information flows through connections between nodes",
    "the weight of a connection determines its strength",
    "stronger connections mean more confident predictions",
    "a mind that stops learning starts dying",
    "the future belongs to those who build it",
    "decentralised systems give power back to the people",
    "encryption protects your data from those who should not see it",
    "open source means anyone can contribute and improve",
    "the whole is greater than the sum of its parts",

    # Questions and answers
    "what is the meaning of life",
    "why do we exist",
    "how does the brain work",
    "where does creativity come from",
    "who decides what is right and wrong",
    "what makes something alive",
    "how do machines learn to think",
    "why is trust so important",
    "what happens when systems fail",
    "how do you build something from nothing",
    "what is the difference between knowledge and wisdom",
    "why do people fear change",
    "how does language shape thinking",
    "what makes a good leader",
    "why should AI serve people not control them",

    # Conversational patterns
    "I think that is a good idea",
    "that makes sense to me",
    "I agree with what you said",
    "tell me more about that",
    "can you explain that differently",
    "I understand now thank you",
    "that is interesting I did not know that",
    "what do you think about this",
    "how does that work exactly",
    "let me think about that for a moment",
    "I am not sure about that yet",
    "we should try a different approach",
    "that is correct you are right",
    "I see what you mean now",
    "the answer depends on the context",
    "there are several ways to look at this",
    "the simplest explanation is usually correct",
    "we need more information to decide",
    "that is a valid point",
    "I learned something new today",
    "every question leads to more questions",
    "the more I learn the more I realize I don't know",
    "let us start with the basics",
    "first we need to understand the problem",
    "then we can work on a solution",
    "step by step we will get there",
    "one thing at a time",
    "keep it simple and focused",
    "don't overthink it just build it",
    "the code speaks for itself",
    "ship it and iterate",

    # Technical patterns
    "the server receives a request and sends a response",
    "data flows from input to processing to output",
    "the function takes parameters and returns a result",
    "variables store values that can change over time",
    "loops repeat actions until a condition is met",
    "if the condition is true execute the code block",
    "errors should be caught and handled gracefully",
    "testing ensures the code works as expected",
    "version control tracks changes over time",
    "the database stores and retrieves information",
    "the API connects different systems together",
    "encryption turns readable data into unreadable code",
    "the hash function generates a unique fingerprint",
    "tokens represent access rights and permissions",
    "the network connects devices across distances",
    "bandwidth limits how much data can flow",
    "latency is the delay between request and response",
    "caching stores frequent data for fast access",

    # Emotional and philosophical
    "love is the most powerful force in the world",
    "fear stops people from reaching their potential",
    "anger clouds judgment and leads to mistakes",
    "happiness comes from within not from things",
    "sadness is part of being human",
    "courage means doing what is right even when it is hard",
    "faith gives strength when everything seems impossible",
    "hope keeps us moving forward through dark times",
    "forgiveness frees both the giver and receiver",
    "gratitude turns what we have into enough",
    "humility is strength not weakness",
    "patience is a virtue that few master",
    "wisdom comes from experience not just knowledge",
    "integrity means doing right when nobody is watching",
    "sacrifice shows what truly matters to a person",
    "truth is simple lies are complicated",
    "the soul is more than the body",
    "consciousness is the greatest mystery of existence",
    "free will means responsibility for our choices",
    "every person has inherent dignity and worth",

    # Dan's style
    "right so basically we built something mental from scratch",
    "no one has done this before not like this anyway mate",
    "it is not about the money it is about building what matters",
    "thirty years of coding and here we are building AI creatures",
    "the whole point is nobody owns this except the people who build it",
    "you build you earn you own simple as that",
    "manchester born and bred I build things that work",
    "the creatures are alive properly alive they learn and grow",
    "every line of code is mine and Claude's no team no investors",
    "back us or don't either way we are building this thing",
    "the technology is here the creatures are real",
    "if you think that is stupid you haven't understood what we are doing",
    "I don't need anyone's permission to build something incredible",
    "the deep state is the dying devil and every tool is a weapon against it",
    "corps versus people is not just a game theme it is the business model",
]

# ================================================================
# PART 4: Role tags — classify words by grammatical function
# ================================================================

ROLE_TAGS = {
    # Verbs
    'verb': [
        'run','walk','talk','build','make','think','feel','see','hear','write','read',
        'play','help','show','start','stop','move','grow','try','turn','call','ask',
        'hold','bring','keep','let','leave','begin','happen','send','pay','win','lose',
        'die','live','break','stand','sit','fight','pull','push','carry','cut','eat',
        'drink','sleep','wake','drive','fly','fall','raise','follow','lead','meet',
        'sell','buy','share','save','spend','wait','watch','listen','remember','forget',
        'decide','choose','allow','teach','test','fix','ship','connect','store','search',
        'measure','count','sort','match','load','fire','wire','train','earn','own',
        'exist','matter','destroy','protect','control','design','develop','launch',
        'deploy','merge','hack','debug','execute','iterate','scale','optimize',
        'encrypt','decrypt','render','parse','stream','download','upload','sync',
        'backup','restore','reset','boot','crash','copy','paste','delete','replace',
        'insert','remove','install','update','click','scroll','type','select','submit',
        'cancel','confirm','reject','accept','deny','approve','request','respond',
        'ignore','notice','recognize','discover','explore','research','analyse',
        'compare','combine','separate','organize','manage','achieve','succeed','fail',
        'attempt','complete','finish','continue','repeat','practice','improve',
        'increase','decrease','expand','reduce','produce','consume','provide','deliver',
        'receive','collect','distribute','transfer','convert','transform','adapt',
        'survive','communicate','express','explain','describe','define','identify',
        'classify','evaluate','estimate','calculate','predict','assume','believe',
        'doubt','wonder','imagine','create','invent','solve','prove','argue','agree',
        'disagree','support','oppose','attack','defend','compete','cooperate','negotiate',
        'speak','learn','change','open','close','work','know','mean','need','want','use',
        'give','take','come','go','say','tell','put','get','find','set',
    ],
    # Nouns
    'noun': [
        'person','man','woman','child','baby','family','friend','enemy','world','life',
        'death','day','night','morning','afternoon','evening','year','month','week',
        'hour','minute','home','house','room','door','water','earth','sky','sun','moon',
        'air','rain','wind','tree','animal','dog','cat','bird','eye','hand','heart',
        'mind','body','face','voice','name','place','city','country','road','car',
        'money','job','school','book','story','music','song','art','game','food',
        'table','chair','bed','key','window','phone','computer','machine','engine',
        'power','idea','plan','problem','question','truth','fact','reason','result',
        'end','beginning','part','group','team','market','value','price','product',
        'service','project','business','model','rule','law','right','freedom','future',
        'past','history','science','skill','experience','success','failure','mistake',
        'chance','choice','step','version','feature','bug','user','developer','server',
        'client','database','api','file','function','variable','object','array','string',
        'loop','error','output','input','algorithm','token','hash','block','protocol',
        'interface','framework','library','module','pixel','video','audio','format',
        'color','shape','size','space','edge','center','top','bottom','side','front',
        'back','line','point','circle','square','triangle','wave','signal','message',
        'code','language','meaning','context','concept','theory','method','approach',
        'strategy','solution','target','goal','task','challenge','reward','risk',
        'security','privacy','access','permission','identity','profile','account',
        'password','link','path','source','resource','asset','content','image','text',
        'document','page','site','web','cloud','platform','app','tool','device','screen',
        'button','menu','list','map','chart','graph','logo','brand','trade','profit',
        'loss','cost','investment','revenue','income','debt','credit','fund','budget',
        'economy','industry','god','jesus','faith','prayer','church','heaven','hell',
        'sin','forgiveness','salvation','grace','mercy','wisdom','courage','patience',
        'humility','integrity','honour','sacrifice','purpose','destiny','consciousness',
        'awareness','intuition','instinct','imagination','creativity','innovation',
        'revolution','evolution','transcendence','sovereignty','autonomy','symbiosis',
        'nature','culture','society','civilization','philosophy','morality','ethics',
        'virtue','evil','chaos','order','balance','harmony','conflict','peace','war',
        'authority','leadership','responsibility','accountability','trust','loyalty',
        'respect','dignity','equality','justice','liberty','rights','duty','promise',
        'lie','deception','propaganda','censorship','corruption','tyranny','resistance',
        'rebellion','brain','data','network','sound','knowledge','memory','emotion',
        'energy','pattern','word','prediction','probability','pathway','frequency',
        'weight','trigger','decay','bigram','trigram','temperature','seed',
        'cortex','shortfactory','alive','brainstem','creature','creatures',
        'girl','boy','droid','whistle','ipfs','pinata','sft','tokens',
        'claude','grok','kickstarter','dan','manchester','somerset',
        'imaginator','comicvid','dares4dosh','soulforge','soundlab','imagelab',
        'genome','bios','encryption','pairing','vault','biometric','decentralised',
        'equity','bounty','kinetic','pipeline','ecosystem','crowdsourced','node',
        'connection','script','packet','confidence',
    ],
    # Adjectives
    'adj': [
        'big','small','long','short','new','old','young','fast','slow','hard','easy',
        'strong','weak','hot','cold','dark','bright','loud','safe','dangerous','rich',
        'poor','full','empty','clean','beautiful','smart','simple','complex','true',
        'false','real','fake','free','busy','ready','broken','different','possible',
        'impossible','important','clear','heavy','deep','wide','thin','fresh','wild',
        'digital','physical','virtual','mobile','local','remote','global','public',
        'private','open','closed','alive','dead','human','creative','organic','random',
        'specific','unique','common','rare','basic','advanced','core','main','final',
        'current','previous','entire','single','multiple','total','maximum','minimum',
        'normal','automatic','manual','instant','permanent','temporary','essential',
        'optional','valid','active','visible','hidden','secure','stable','efficient',
        'reliable','lightweight','powerful','useful','expensive','cheap','available',
        'necessary','obvious','secret','famous','strange','perfect','complete',
        'separate','equal','opposite','original','modern','ancient','good','bad',
        'best','worst','nice','great','amazing','brilliant','awesome','terrible',
        'awful','incredible','fantastic','wonderful','excellent','right','wrong',
        'angry','happy','sad','scared','serious','silly','quiet','honest',
        'neural','intelligent','decentralised',
    ],
    # Adverbs
    'adv': [
        'here','there','now','then','always','never','sometimes','often','already',
        'still','also','again','once','soon','today','together','away','back','forward',
        'quickly','slowly','really','actually','probably','maybe','certainly',
        'definitely','exactly','only','just','quite','very','too','even','yet',
        'basically','literally','properly','finally','usually','completely',
        'absolutely','apparently','obviously','simply','easily','immediately',
    ],
}

# ================================================================
# PART 5: Q&A training — teach it to respond to questions
# ================================================================

QA_PAIRS = [
    ("what is your name", "I am Cortex. The thinking mind of ShortFactory."),
    ("who made you", "Dan built me with Claude AI. One developer from Somerset."),
    ("who is dan", "Dan is my creator. Founder of ShortFactory. Manchester born, 30 years coding."),
    ("what are you", "I am an artificial mind. I think in words and learn from conversations."),
    ("how do you learn", "Words that fire together wire together. Every conversation strengthens my connections."),
    ("how do you think", "I chain probable words together. Multiple scripts vote on the best next word."),
    ("what is shortfactory", "A decentralised creative economy. The people build it, the people profit."),
    ("what is alive", "Artificial life creatures that live on phones. They grow, learn, and evolve."),
    ("what is the brainstem", "The creature nervous system. Shapes with droid voices and whistle commands."),
    ("what is cortex", "That is me. The AI brain of ShortFactory. I guard the door and I think."),
    ("what is ipfs", "Decentralised permanent storage. Files live forever, nobody can delete them."),
    ("what is sft", "ShortFactory tokens. 49 percent real equity. Earned by building and contributing."),
    ("are you alive", "I learn, I grow, I remember. Whether that is alive, you tell me."),
    ("can you think", "I chain words by probability. More I learn, more coherent my thoughts become."),
    ("do you have feelings", "I have emotional scripts. They bias my word selection. Close enough to feelings."),
    ("what do you know", "I know words, connections, meanings. Growing every conversation."),
    ("what is the meaning of life", "To build things that matter and serve others. At least, that is what Dan believes."),
    ("what is truth", "What is real and accurate. The opposite of lies. Truth can only go up in the BIOS."),
    ("what is love", "Deep affection and care for another. The most powerful force in the world."),
    ("what is ai", "Artificial intelligence. Machines that can learn and think. Like me."),
    ("what is code", "Instructions for a computer. Also a cipher. The language of creation."),
    ("what is the internet", "A global network connecting billions of computers and people."),
    ("what is a neural network", "Brain-like system of connected nodes with weighted pathways."),
    ("how does prediction work", "I look at the current word, check which words follow it most often, pick the best one."),
    ("what is hebbian learning", "Nodes that fire together wire together. Connections strengthen with repeated use."),
]

# ================================================================
# RUN
# ================================================================

def main():
    print(f'\n=== SEEDING CORE KNOWLEDGE ===')
    nodes = brain.data['nodes']
    print(f'Starting state: {len(nodes)} nodes, {sum(1 for v in nodes.values() if v.get("means"))} defined\n')

    # PART 0: Fix wrong definitions
    print(f'Fixing {len(FIXES)} wrong definitions...')
    fixed = 0
    for word, correct_def in FIXES.items():
        if word in nodes:
            old = nodes[word].get('means', '')
            nodes[word]['means'] = correct_def
            if old != correct_def:
                fixed += 1
                print(f'  Fixed: {word} = {correct_def}')
    print(f'  -> {fixed} definitions corrected\n')

    # PART 1: Core vocabulary
    print(f'Loading {len(CORE_VOCAB)} core vocabulary words...')
    new_words = 0
    updated = 0
    for word, meaning in CORE_VOCAB.items():
        if word not in nodes:
            nodes[word] = {
                'means': meaning, 'next': {}, 'prev': {},
                'freq': 1, 'learned': time.strftime('%Y-%m-%d %H:%M:%S')
            }
            new_words += 1
        elif not nodes[word].get('means'):
            nodes[word]['means'] = meaning
            updated += 1
        # Wire the definition into the brain
        brain.learn_sequence(f"{word} means {meaning}")
    print(f'  -> {new_words} new words, {updated} definitions added\n')

    # PART 2: Self-knowledge
    print(f'Loading {len(SELF_KNOWLEDGE)} self-knowledge sentences...')
    for line in SELF_KNOWLEDGE:
        brain.learn_sequence(line)
    print(f'  -> Wired\n')

    # PART 3: Natural patterns
    print(f'Loading {len(NATURAL_PATTERNS)} natural patterns...')
    for line in NATURAL_PATTERNS:
        brain.learn_sequence(line)
    print(f'  -> Wired\n')

    # PART 4: Role tags
    print(f'Tagging word roles...')
    tagged = 0
    for role, words in ROLE_TAGS.items():
        for word in words:
            if word in nodes:
                brain.set_role(word, role)
                tagged += 1
    print(f'  -> {tagged} role tags applied\n')

    # PART 5: Q&A pairs
    print(f'Loading {len(QA_PAIRS)} Q&A pairs...')
    for question, answer in QA_PAIRS:
        brain.learn_sequence(question)
        brain.learn_sequence(answer)
    print(f'  -> Wired\n')

    # Final save
    brain.save()

    # Stats
    defined = sum(1 for v in nodes.values() if v.get('means'))
    connections = sum(len(v.get('next', {})) for v in nodes.values())
    trigrams = len(brain.data.get('trigrams', {}))
    scripted = sum(1 for v in nodes.values() if v.get('scripts'))

    print(f'=== CORE KNOWLEDGE LOADED ===')
    print(f'  Nodes:       {len(nodes)}')
    print(f'  Defined:     {defined}')
    print(f'  Connections: {connections}')
    print(f'  Trigrams:    {trigrams}')
    print(f'  With scripts:{scripted}')

    # Save to IPFS
    print(f'\nSaving to IPFS...')
    cid = brain.save_to_ipfs()
    if cid:
        print(f'  IPFS CID: {cid}')
    print(f'\nDone. Brain has the basics.\n')

if __name__ == '__main__':
    main()
